import React, { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { Search, BookOpen, Bookmark, Compass, Settings, Plus, MoreHorizontal, ArrowUpRight, Clock3, CheckCircle2, PauseCircle, LibraryBig, ChevronRight, SlidersHorizontal, Download, Upload, Trash2, X, ExternalLink, Play, Pencil, Menu, Sparkles } from 'lucide-react'
import './styles.css'

const genres = ['Fantasy','Dark Fantasy','Cultivation','Xianxia','Wuxia','Action','Adventure','Mystery','Thriller','Horror','Romance','Comedy','Drama','Sci-Fi','Psychological','Supernatural','Time Loop','Academy','System','Regression','Reincarnation','Other']
const coverImages = {
  'Lord of Mysteries': 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=600&q=85',
  'Mother of Learning': 'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&w=600&q=85',
  'Reverend Insanity': 'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?auto=format&fit=crop&w=600&q=85',
  "The Author's POV": 'https://images.unsplash.com/photo-1519682337058-a94d519337bc?auto=format&fit=crop&w=600&q=85',
  "The Novel's Extra": 'https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&w=600&q=85',
  "An Alchemist's Path to Eternity": 'https://images.unsplash.com/photo-1511108690759-009c619f27ca?auto=format&fit=crop&w=600&q=85'
}
const seed = [
  { id: 'lom', title: 'Lord of Mysteries', alt: '诡秘之主', author: 'Cuttlefish That Loves Diving', genres: ['Fantasy','Mystery','Supernatural','Action'], status: 'Reading', chapter: 42, total: 1432, rating: 5, source: 'Placeholder source', url: 'https://example.com/replace-with-legitimate-source', description: 'In a world of steam, machinery, and mysticism, Klein Moretti wakes into a life threaded with secrets. Every ritual, artifact, and step upward carries a cost.', lastOpened: 'Today', added: '2026-07-28', notes: 'The fog and ritual sequences are wonderfully atmospheric.', cover: coverImages['Lord of Mysteries'], favorite: true },
  { id: 'mol', title: 'Mother of Learning', alt: '—', author: 'nobody103', genres: ['Fantasy','Time Loop','Academy','Action'], status: 'Reading', chapter: 17, total: 108, rating: 5, source: 'Placeholder source', url: 'https://example.com/replace-with-legitimate-source', description: 'Zorian is a teenage mage trapped in a time loop. Each repetition is an opportunity to learn, prepare, and uncover the force behind the catastrophe.', lastOpened: 'Yesterday', added: '2026-07-25', notes: '', cover: coverImages['Mother of Learning'], favorite: false },
  { id: 'ri', title: 'Reverend Insanity', alt: '蛊真人', author: 'Gu Zhen Ren', genres: ['Dark Fantasy','Cultivation','Xianxia','Psychological'], status: 'On Hold', chapter: 311, total: 2334, rating: 4, source: 'Placeholder source', url: 'https://example.com/replace-with-legitimate-source', description: 'A ruthless return to the beginning. Fang Yuan walks the immortal path with five hundred years of memory and no room for sentiment.', lastOpened: '12 Jul 2026', added: '2026-07-21', notes: '', cover: coverImages['Reverend Insanity'], favorite: true },
  { id: 'apov', title: "The Author's POV", alt: 'Author’s Point of View', author: 'Entrail_Ji', genres: ['Action','Fantasy','System','Regression'], status: 'Plan to Read', chapter: 0, total: 700, rating: 0, source: 'Placeholder source', url: 'https://example.com/replace-with-legitimate-source', description: 'A writer wakes inside his own unfinished novel, except he is not the protagonist. The world knows the rules—but not all of them.', lastOpened: 'Never', added: '2026-07-18', notes: '', cover: coverImages["The Author's POV"], favorite: false },
  { id: 'tne', title: "The Novel's Extra", alt: '소설 속 엑스트라', author: 'Jee Gab Song', genres: ['Action','Fantasy','Academy','Drama'], status: 'Completed', chapter: 376, total: 376, rating: 4, source: 'Placeholder source', url: 'https://example.com/replace-with-legitimate-source', description: 'Kim Hajin finds himself as a disposable extra in the novel he wrote, armed with a gun, a notebook, and a fading memory of the plot.', lastOpened: '03 Jun 2026', added: '2026-07-10', notes: 'Finished — revisit the early academy arc.', cover: coverImages["The Novel's Extra"], favorite: false },
  { id: 'aep', title: "An Alchemist's Path to Eternity", alt: '—', author: 'Ming Yue', genres: ['Fantasy','Adventure','Reincarnation'], status: 'Plan to Read', chapter: 0, total: 520, rating: 0, source: 'Placeholder source', url: 'https://example.com/replace-with-legitimate-source', description: 'A second life, a broken formula, and the long road toward a philosopher’s stone that may not be a stone at all.', lastOpened: 'Never', added: '2026-07-06', notes: '', cover: coverImages["An Alchemist's Path to Eternity"], favorite: false }
]

function App() {
  const [novels, setNovels] = useState(() => { try { return JSON.parse(localStorage.getItem('marang-library')) || seed } catch { return seed } })
  const [view, setView] = useState('home'), [selected, setSelected] = useState(null), [query, setQuery] = useState(''), [status, setStatus] = useState('All statuses'), [sort, setSort] = useState('Recently opened'), [activeGenres, setActiveGenres] = useState([]), [modal, setModal] = useState(false), [mobileNav, setMobileNav] = useState(false)
  useEffect(() => localStorage.setItem('marang-library', JSON.stringify(novels)), [novels])
  const openNovel = (novel) => { setNovels(xs => xs.map(x => x.id === novel.id ? {...x, lastOpened: 'Just now'} : x)); setSelected(novel.id); setView('details'); setMobileNav(false) }
  const filtered = useMemo(() => novels.filter(n => (!query || [n.title,n.alt,n.author,...n.genres].join(' ').toLowerCase().includes(query.toLowerCase())) && (status === 'All statuses' || n.status === status) && (!activeGenres.length || activeGenres.every(g => n.genres.includes(g)))).sort((a,b) => sort === 'A–Z' ? a.title.localeCompare(b.title) : sort === 'Author' ? a.author.localeCompare(b.author) : sort === 'Rating' ? b.rating-a.rating : sort === 'Recently added' ? b.added.localeCompare(a.added) : (b.lastOpened === 'Never') - (a.lastOpened === 'Never')), [novels,query,status,sort,activeGenres])
  const current = novels.find(n => n.id === selected)
  const update = (id, patch) => setNovels(xs => xs.map(n => n.id === id ? {...n,...patch} : n))
  const exportData = () => { const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([JSON.stringify(novels,null,2)],{type:'application/json'})); a.download='marang-archive-backup.json'; a.click() }
  const importData = (e) => { const file=e.target.files?.[0]; if(!file)return; const r=new FileReader(); r.onload=()=>{try{setNovels(JSON.parse(r.result))}catch{alert('That file is not a valid archive backup.')}}; r.readAsText(file) }
  return <div className="app-shell">
    <aside className={mobileNav ? 'sidebar open' : 'sidebar'}><div className="brand"><div className="brand-mark">M</div><div><div className="brand-name">THE MARANG</div><div className="brand-sub">ARCHIVE</div></div><button className="mobile-close" onClick={()=>setMobileNav(false)}><X size={18}/></button></div><div className="rule"/>
      <nav><Nav icon={<Compass/>} label="Overview" active={view==='home'} onClick={()=>{setView('home');setSelected(null);setMobileNav(false)}}/><Nav icon={<LibraryBig/>} label="My Library" active={view==='library'} onClick={()=>{setView('library');setSelected(null);setMobileNav(false)}}/><Nav icon={<Bookmark/>} label="Bookmarks" active={view==='bookmarks'} onClick={()=>{setView('bookmarks');setSelected(null);setMobileNav(false)}}/></nav>
      <div className="side-label">YOUR SHELVES</div><div className="shelf"><span className="dot reading"/>Currently reading <span>{novels.filter(n=>n.status==='Reading').length}</span></div><div className="shelf"><span className="dot gold"/>Plan to read <span>{novels.filter(n=>n.status==='Plan to Read').length}</span></div><div className="shelf"><span className="dot green"/>Completed <span>{novels.filter(n=>n.status==='Completed').length}</span></div>
      <div className="sidebar-bottom"><div className="side-label">ARCHIVE TOOLS</div><button className="side-tool" onClick={exportData}><Download size={16}/> Export archive</button><label className="side-tool"><Upload size={16}/> Import backup<input type="file" accept="application/json" hidden onChange={importData}/></label><button className="side-tool" onClick={()=>setModal(true)}><Plus size={16}/> Add a novel</button></div>
      <div className="profile"><div className="avatar">S</div><div><b>Storykeeper</b><small>Personal archive</small></div><Settings size={16}/></div>
    </aside>
    <main><header><button className="menu-btn" onClick={()=>setMobileNav(true)}><Menu/></button><div className="breadcrumbs">THE MARANG ARCHIVE <span>/</span> {view==='home'?'OVERVIEW':view.toUpperCase()}</div><div className="header-actions"><div className="header-search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search the archive..."/><kbd>⌘ K</kbd></div><button className="add-btn" onClick={()=>setModal(true)}><Plus size={16}/> <span>Add novel</span></button></div></header>
      {view==='home' && <Dashboard novels={novels} openNovel={openNovel} goLibrary={()=>setView('library')}/>} {view==='library' && <Library novels={filtered} query={query} status={status} setStatus={setStatus} sort={sort} setSort={setSort} activeGenres={activeGenres} setActiveGenres={setActiveGenres} openNovel={openNovel}/>} {view==='bookmarks' && <Library novels={novels.filter(n=>n.favorite || n.status==='Plan to Read')} query={query} status="All statuses" setStatus={()=>{}} sort={sort} setSort={setSort} activeGenres={[]} setActiveGenres={()=>{}} openNovel={openNovel}/>} {view==='details' && current && <Details novel={current} update={update} back={()=>{setView('library');setSelected(null)}}/>}
    </main>{modal && <AddModal close={()=>setModal(false)} add={n=>{setNovels(xs=>[n,...xs]);setModal(false)}}/>}
  </div>
}
function Nav({icon,label,active,onClick}) { return <button className={active?'nav-item active':'nav-item'} onClick={onClick}>{React.cloneElement(icon,{size:18})}<span>{label}</span>{active&&<i/>}</button> }
function Dashboard({novels,openNovel,goLibrary}) { const reading=novels.filter(n=>n.status==='Reading'); const recent=novels.filter(n=>n.lastOpened!=='Never').slice(0,3); return <div className="content dashboard"><section className="hero"><div><div className="eyebrow"><Sparkles size={13}/> YOUR PRIVATE READING ROOM</div><h1>Stories worth<br/><em>returning to.</em></h1><p>An archive of stories, worlds, and journeys.<br/>Keep your place. Follow the thread.</p><button className="primary" onClick={()=>reading[0]&&openNovel(reading[0])}><Play size={16} fill="currentColor"/> Continue reading</button></div><div className="hero-orbit"><div className="orbit-ring ring-one"/><div className="orbit-ring ring-two"/><div className="hero-book">✦<small>EST.<br/>2026</small></div><span className="orbit-note note-one">A quiet place<br/>for loud worlds.</span><span className="orbit-note note-two">Vol. I —</span></div></section><div className="section-heading"><div><div className="eyebrow">AT A GLANCE</div><h2>Your reading room</h2></div><button className="text-btn" onClick={goLibrary}>View library <ArrowUpRight size={15}/></button></div><div className="stat-grid"><Stat label="In progress" value={reading.length} note="stories underway" icon={<Clock3/>}/><Stat label="Pages turned" value="1,284" note="across your archive" icon={<BookOpen/>}/><Stat label="Completed" value={novels.filter(n=>n.status==='Completed').length} note="worlds visited" icon={<CheckCircle2/>}/><Stat label="Bookmarks" value={novels.filter(n=>n.favorite).length} note="marked for later" icon={<Bookmark/>}/></div><div className="two-col"><section><div className="section-heading compact"><div><div className="eyebrow">PICK UP WHERE YOU LEFT OFF</div><h2>Continue reading</h2></div><button className="icon-btn"><MoreHorizontal size={18}/></button></div>{reading.slice(0,2).map(n=><ProgressRow key={n.id} novel={n} openNovel={openNovel}/>)}</section><section><div className="section-heading compact"><div><div className="eyebrow">RECENTLY OPENED</div><h2>Back on the shelf</h2></div></div><div className="recent-stack">{recent.map(n=><MiniRow key={n.id} novel={n} openNovel={openNovel}/>)}</div></section></div></div> }
function Stat({label,value,note,icon}){return <div className="stat"><div className="stat-icon">{icon}</div><div><div className="stat-label">{label}</div><strong>{value}</strong><small>{note}</small></div></div>}
function ProgressRow({novel,openNovel}){const p=novel.total?Math.round(novel.chapter/novel.total*100):0;return <button className="progress-row" onClick={()=>openNovel(novel)}><img src={novel.cover}/><div className="row-main"><div className="row-top"><b>{novel.title}</b><span>{novel.chapter} / {novel.total}</span></div><div className="muted">Chapter {novel.chapter} · {novel.author}</div><div className="bar"><i style={{width:`${Math.max(p,2)}%`}}/></div><div className="row-bottom"><span>{p}% complete</span><span>Last read {novel.lastOpened}</span></div></div><ChevronRight size={17}/></button>}
function MiniRow({novel,openNovel}){return <button className="mini-row" onClick={()=>openNovel(novel)}><img src={novel.cover}/><div><b>{novel.title}</b><small>{novel.author}</small></div><span>{novel.lastOpened}</span></button>}
function Library({novels,query,status,setStatus,sort,setSort,activeGenres,setActiveGenres,openNovel}){return <div className="content"><div className="page-intro"><div><div className="eyebrow">THE COLLECTION</div><h1>My library <span>{novels.length}</span></h1><p>Every story has a place. Find yours.</p></div><button className="filter-toggle"><SlidersHorizontal size={16}/> Filters</button></div><div className="library-controls"><div className="genre-scroll"><button className={!activeGenres.length?'chip selected':'chip'} onClick={()=>setActiveGenres([])}>All genres</button>{genres.map(g=><button key={g} className={activeGenres.includes(g)?'chip selected':'chip'} onClick={()=>setActiveGenres(activeGenres.includes(g)?activeGenres.filter(x=>x!==g):[...activeGenres,g])}>{g}</button>)}</div><div className="selects"><select value={status} onChange={e=>setStatus(e.target.value)}><option>All statuses</option><option>Reading</option><option>Completed</option><option>On Hold</option><option>Plan to Read</option></select><select value={sort} onChange={e=>setSort(e.target.value)}><option>Recently opened</option><option>Recently added</option><option>A–Z</option><option>Author</option><option>Rating</option></select></div></div>{novels.length?<div className="book-grid">{novels.map(n=><NovelCard key={n.id} novel={n} openNovel={openNovel}/>)}</div>:<div className="empty"><BookOpen size={28}/><h3>No stories found</h3><p>Try a different title, genre, or status.</p></div>}</div>}
function NovelCard({novel,openNovel}){const p=novel.total?Math.round(novel.chapter/novel.total*100):0;return <button className="novel-card" onClick={()=>openNovel(novel)}><div className="cover-wrap"><img src={novel.cover}/><div className="status-pill"><span className={`dot ${novel.status==='Completed'?'green':novel.status==='Reading'?'reading':'gold'}`}/>{novel.status}</div>{novel.favorite&&<div className="fav">★</div>}</div><div className="card-copy"><h3>{novel.title}</h3><div className="alt">{novel.alt}</div><div className="author">{novel.author}</div><div className="tag-list">{novel.genres.slice(0,2).map(g=><span key={g}>{g}</span>)}</div><div className="card-progress"><div className="bar"><i style={{width:`${Math.max(p,novel.chapter?2:0)}%`}}/></div><span>{novel.chapter?`${p}% · Ch. ${novel.chapter}`:'Not started'}</span></div></div></button>}
function Details({novel,update,back}){const p=novel.total?Math.round(novel.chapter/novel.total*100):0; const [chapter,setChapter]=useState(novel.chapter); return <div className="content detail"><button className="back" onClick={back}>← Back to library</button><div className="detail-layout"><div className="detail-cover"><img src={novel.cover}/><div className="cover-caption">THE MARANG ARCHIVE<br/><span>VOLUME {novel.id.toUpperCase()}</span></div></div><div className="detail-main"><div className="eyebrow">NOVEL RECORD · {novel.status.toUpperCase()}</div><h1>{novel.title}</h1><div className="detail-alt">{novel.alt}</div><div className="detail-author">by <b>{novel.author}</b></div><div className="detail-tags">{novel.genres.map(g=><span key={g}>{g}</span>)}</div><p className="description">{novel.description}</p><div className="detail-actions"><button className="primary" onClick={()=>window.open(novel.url,'_blank','noopener,noreferrer')}><ExternalLink size={16}/> Start reading</button><button className={novel.favorite?'secondary active-fav':'secondary'} onClick={()=>update(novel.id,{favorite:!novel.favorite})}><Bookmark size={16} fill={novel.favorite?'currentColor':'none'}/> {novel.favorite?'Bookmarked':'Bookmark'}</button></div><div className="gateway-note"><ExternalLink size={15}/><span><b>{novel.source}</b><br/><small>External website · Opens in a new tab. The archive does not host or copy reading content.</small></span></div></div></div><div className="detail-lower"><section className="tracker-panel"><div className="panel-title"><div><div className="eyebrow">PERSONAL TRACKER</div><h2>Your progress</h2></div><span className="percent">{p}%</span></div><div className="big-bar"><i style={{width:`${p}%`}}/></div><div className="tracker-inputs"><label>Current chapter<input type="number" value={chapter} onChange={e=>setChapter(e.target.value)} onBlur={()=>update(novel.id,{chapter:Number(chapter),status:Number(chapter)>0&&novel.status==='Plan to Read'?'Reading':novel.status,lastOpened:'Today'})}/></label><label>Total chapters<input type="number" value={novel.total} onChange={e=>update(novel.id,{total:Number(e.target.value)})}/></label><label>Status<select value={novel.status} onChange={e=>update(novel.id,{status:e.target.value})}><option>Reading</option><option>Completed</option><option>On Hold</option><option>Plan to Read</option></select></label></div></section><section className="notes-panel"><div className="eyebrow">PRIVATE NOTES</div><h2>Keeper’s notes</h2><textarea value={novel.notes} onChange={e=>update(novel.id,{notes:e.target.value})} placeholder="Leave a note for your future self..."/><div className="note-save">Saved locally · only visible to you</div></section></div></div>}
function AddModal({close,add}){const [title,setTitle]=useState(''),[author,setAuthor]=useState(''),[url,setUrl]=useState('');return <div className="modal-backdrop"><div className="modal"><button className="modal-close" onClick={close}><X size={18}/></button><div className="eyebrow">NEW RECORD</div><h2>Add a novel</h2><p className="muted">Create a personal entry for a story you want to keep close.</p><label>Title<input autoFocus value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. The Name of the Wind"/></label><label>Author<input value={author} onChange={e=>setAuthor(e.target.value)} placeholder="Author name"/></label><label>Legitimate reading URL<input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://..."/></label><button className="primary full" disabled={!title} onClick={()=>add({id:Date.now().toString(),title,alt:'—',author:author||'Unknown author',genres:['Other'],status:'Plan to Read',chapter:0,total:0,rating:0,source:'Your reading source',url:url||'https://example.com',description:'Add a description from your own notes.',lastOpened:'Never',added:new Date().toISOString(),notes:'',cover:'https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&w=600&q=85',favorite:false})}><Plus size={16}/> Add to archive</button></div></div>}
createRoot(document.getElementById('root')).render(<App />)
